spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    password: admin
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

demo:
  security.jwt:
    tokenExpirationTime: 86400
    tokenSigningKey: jwtGrokonezSecretKey
